services:

  es01:
    container_name: es01
    image: elasticsearch:8.11.3
    networks:
      - elastic
    ports:
      - "9200:9200"
    mem_limit: 1g
    environment:
      xpack.security.enabled: false
      xpack.security.http.ssl.enabled: false
      discovery.type: single-node
      xpack.ml.enabled: false

  kibana:
    container_name: kibana
    image: kibana:8.11.3
    networks:
      - elastic
    ports:
      - "5601:5601"
    restart: always
    environment:
      - ELASTICSEARCH_URL=http://es01:9200
    depends_on:
      - es01

networks:
  elastic:
    driver: bridge